spring.application.name=screensound_db
spring.datasource.url=jdbc:mysql://${DB_HOST}/screensound_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

// Instrui o JPA a criar a tabela automaticamente na primeira vez
spring.jpa.hibernate.ddl-auto=update